spring:
  application:
    name: fundamentos01-api

  profiles:
    active: dev
  web:
    error:
      include-message: always
      include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

info:
  app:
    name: fundamentos01-api
    description: API REST con Spring Boot, PostgreSQL, JWT, roles y ownership
    version: 1.0.0